# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: ChatWithMe
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRING_DATA_MONGODB_URI: mongodb+srv://root:root@chatapp.axbza.mongodb.net/chatapp?retryWrites=true &w=majority
      SPRING_DATA_MONGODB_DATABASE: chatapp
      SPRING_DATA_MONGODB_SSL_ENABLED: "true"
      FIREBASE_DATABASE_URL: https://chatwithme-033-default-rtdb.firebaseio.com
      FIREBASE_SERVICE_ACCOUNT_FILE_PATH: /app/config/key/chatwithme-033-firebase-adminsdk-stxjp-4933c87581.json
      SPRING_MVC_STATIC_PATH_PATTERN: /**
      SERVER_COMPRESSION_ENABLED: "true"
      SERVER_COMPRESSION_MIME_TYPES: application/json,application/xml,text/html,text/plain
      SERVER_COMPRESSION_MIN_RESPONSE_SIZE: 1024
      SPRING_SERVLET_MULTIPART_ENABLED: "true"
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
    volumes:
      - ./config:/app/config
    # depends_on:
    #   - mongo

  # mongo:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_DATABASE: chatapp
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   volumes:
  #     - mongodb_data:/data/db

volumes:
  mongodb_data:
